### ISSUE TITLE
ロゴとタイトル入れたい

### ISSUE THREAD

**Issue by Tonkyu** [Tonkyu/mu-life-front#1]
ロゴとタイトルを決めて入れたい
ブラウザの上部に表示されるやつ

**Comment by 1ksummmers** [comment]
@Tonkyu 
テスト

**Comment by 1ksummmers** [comment]
@Tonkyu 

サービス名3つと、それぞれに対してオレンジ色のロゴをA案・B案を考えてみました。
気に入ったものありますか〜？

ちなみにロゴがブラウザタブのアイコン（favicon）になるイメージです。
![logo1-](https://user-images.githubusercontent.com/124763128/227377056-98b696b4-5a58-4d75-b5df-c9831b925c6c.jpg)
![logo2](https://user-images.githubusercontent.com/124763128/227377063-1adc5fdc-e153-497b-b6b4-bf5f19bf010b.jpg)
![logo3-](https://user-images.githubusercontent.com/124763128/227377065-01715edd-e038-41ac-80bd-9b32bb56a77a.jpg)

**Comment by Tonkyu** [comment]
@1ksummmers 
すごすぎる、、どれもめっちゃいいですね！
一つに決めきれなくて申し訳ないんですけど、タイトルはPinTrack、アイコンはSoundPinのAがお気に入りです！

**Comment by 1ksummmers** [comment]
@Tonkyu 
確認ありがとうございます！
ではロゴ＆タイトルはこれで。後ほど作業してpushします！
<img width="1237" alt="スクリーンショット 2023-03-25 11 49 34" src="https://user-images.githubusercontent.com/124763128/227683894-f8fe6ef6-2063-4ce6-a812-6a5bd4043b91.png">

**Comment by 1ksummmers** [comment]
入れたのでClose
